# Generated by Django 4.2.7 on 2026-02-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_document',
            field=models.ImageField(blank=True, null=True, upload_to='identity_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
    ]
