# Generated by Django 4.2.7 on 2026-02-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_identity_document_user_is_identity_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingVerification',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Identity Verification',
                'verbose_name_plural': 'Pending Identity Verifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
