# Generated by Django 4.2.7 on 2026-02-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistrationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pre-Registration OTP',
                'verbose_name_plural': 'Pre-Registration OTPs',
            },
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('Registration', 'Registration'), ('PasswordReset', 'PasswordReset')], default='Registration', max_length=20),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
