# Generated by Django 4.2.7 on 2026-02-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_preregistrationotp_phoneotp_phone_phoneotp_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Owner', 'Owner'), ('Tenant', 'Tenant')], max_length=10),
        ),
    ]
