# Generated by Django 4.2.7 on 2026-02-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_rejection_reason_user_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Tenant', 'Tenant'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
