# Generated by Django 4.2.7 on 2026-02-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_platformpolicy_remove_user_rejection_reason_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformPolicy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rejection_reason',
        ),
    ]
