# Generated by Django 4.2.7 on 2026-02-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('booking_request', 'New Booking Request'), ('booking_accepted', 'Booking Accepted'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('visit_requested', 'New Visit Request'), ('visit_approved', 'Visit Approved'), ('visit_rejected', 'Visit Rejected'), ('visit_cancelled', 'Visit Cancelled'), ('rent_reminder', 'Rent Due Reminder'), ('payment_received', 'Payment Received')], max_length=20),
        ),
    ]
