# Generated by Django 4.2.7 on 2026-02-05 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OwnerRooms', '0007_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('payment_type', models.CharField(choices=[('Rent', 'Rent'), ('Deposit', 'Deposit'), ('Maintenance', 'Maintenance')], default='Rent', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('eSewa', 'eSewa'), ('Khalti', 'Khalti'), ('Cash', 'Cash'), ('Other', 'Other')], max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='OwnerRooms.booking')),
            ],
            options={
                'db_table': 'OwnerRooms_payment',
                'ordering': ['due_date'],
            },
        ),
    ]
