# Generated by Django 6.0 on 2026-01-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerRooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='gender_preference',
            field=models.CharField(choices=[('Any', 'Any'), ('Male', 'Male'), ('Female', 'Female')], default='Any', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for map location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for map location', max_digits=9, null=True),
        ),
    ]
