# Generated by Django 6.0 on 2026-02-01 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerRooms', '0002_room_gender_preference_room_latitude_room_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('gender_preference', models.CharField(blank=True, max_length=20, null=True)),
                ('room_type', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
