# Generated by Django 6.0 on 2026-02-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerRooms', '0003_booking_chat_payment_usersearchpreference_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='attached_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='furniture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='water_supply',
            field=models.BooleanField(default=False),
        ),
    ]
