# Generated by Django 4.2.7 on 2026-02-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerRooms', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('eSewa', 'eSewa'), ('Khalti', 'Khalti'), ('Cash', 'Cash'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
