# Generated by Django 4.2.7 on 2026-02-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerRooms', '0006_payment_fields_fix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
