# Generated by Django 4.2.7 on 2026-02-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerRooms', '0010_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='room',
            name='attached_bathroom',
        ),
        migrations.RemoveField(
            model_name='room',
            name='cctv',
        ),
        migrations.RemoveField(
            model_name='room',
            name='furniture',
        ),
        migrations.RemoveField(
            model_name='room',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tv',
        ),
        migrations.AddField(
            model_name='room',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='cooking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='drinking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='electricity_backup',
            field=models.CharField(choices=[('Inverter', 'Inverter'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='kitchen_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='preferred_tenant',
            field=models.CharField(choices=[('Any', 'Any'), ('Students', 'Students'), ('Working Professionals', 'Working Professionals'), ('Family', 'Family')], default='Any', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='toilet_type',
            field=models.CharField(choices=[('Attached', 'Attached'), ('Shared', 'Shared')], default='Shared', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='visitor_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Shared Room', 'Shared Room'), ('Family Room', 'Family Room'), ('Apartment', 'Apartment')], default='Single Room', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Available', 'Available'), ('Rented', 'Rented'), ('Disabled', 'Disabled')], default='Pending Verification', max_length=20),
        ),
    ]
