# Generated by Django 4.2.7 on 2026-02-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerRooms', '0011_remove_room_ac_remove_room_attached_bathroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearchpreference',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='usersearchpreference',
            name='tv',
        ),
        migrations.AddField(
            model_name='usersearchpreference',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersearchpreference',
            name='kitchen_access',
            field=models.BooleanField(default=False),
        ),
    ]
