# Generated by Django 4.2.7 on 2026-02-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerRooms', '0012_remove_usersearchpreference_ac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Available', 'Available'), ('Rented', 'Rented'), ('Disabled', 'Disabled')], default='Available', max_length=20),
        ),
    ]
