# Generated by Django 4.2.7 on 2026-02-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerRooms', '0013_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Available', 'Available'), ('Occupied', 'Occupied'), ('Rented', 'Rented'), ('Disabled', 'Disabled')], default='Available', max_length=20),
        ),
    ]
