# Generated by Django 4.2.7 on 2026-02-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerRooms', '0014_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated amenities'),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
