# Generated by Django 4.2.7 on 2026-02-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerRooms', '0015_room_amenities_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='attached_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersearchpreference',
            name='ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersearchpreference',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
    ]
