# Generated by Django 4.2.7 on 2026-02-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerRooms', '0016_remove_usersearchpreference_furnished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearchpreference',
            name='kitchen_access',
        ),
        migrations.AddField(
            model_name='room',
            name='ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersearchpreference',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
    ]
