# Generated by Django 4.2.7 on 2026-02-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerRooms', '0018_alter_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
    ]
